//
// Created by morrigan on 3/10/19.
//

#include <iostream>
#include <string>
#include <regex>
#include <thread>

#include <ngspice/sharedspice.h>

using namespace std;

// Callback functions called by NgSpice thread

/*
 * callback function for reading printf, fprintf, fput (NULL allowed)
 */
int getchar_cb(char* outputreturn, int ident, void* userdata){
    string msg(outputreturn);
    if(!msg.find("stderr")){
        cerr << regex_replace(msg, regex("stderr"), "") << endl;
    }else{
        cout << regex_replace(msg, regex("stdout"), "") << endl;
    }
    return 0;
}

/*
 * callback function for reading status string and percent value (NULL allowed)
 */
int getstat_cb(char* outputreturn, int ident, void* userdata){
    string msg(outputreturn);
    //cout << msg << endl;
    return 0;
}

/*
 * callback function for sending an array of structs containing data values of all
 * vectors in the current plot (simulation output) (NULL allowed)
 */
int data_cb(pvecvaluesall vdata, int numvecs, int ident, void* userdata)
{
    //return 0;
    cout << "data_cb: "
    << "numvecs = " << numvecs
    << ", veccount = " << vdata->veccount
            << ", vecindex = " << vdata->vecindex << endl;
    for(int i = 0; i < vdata->veccount; i++){
        cout << string(vdata->vecsa[i]->name)
        << " = {" << vdata->vecsa[i]->creal << ","
        << vdata->vecsa[i]->cimag << "}" << endl;
    }

    return 0;
}

/*
 * callback function for sending an array of structs containing info on all vectors in the
 * current "plot" (immediately before simulation starts) (NULL allowed)
 *
 * This function is called each time the simulation starts from the beginning. If we
 * "bg_halt" the simulation and call "bg_run" afterwards - thsi function will be called
 * for the second time.
 */
int initdata_cb(pvecinfoall intdata, int ident, void* userdata)
{
    cout << "\n\nINIT DATA" << endl;
    cout << "name: " << string(intdata->name) << endl;
    cout << "title: " << string(intdata->title) << endl;
    cout << "date: " << string(intdata->date) << endl;
    cout << "type: " << string(intdata->type) << endl;

    cout << "vectors: ";
    for(int i = 0; i < intdata->veccount; i++){
        cout << string(intdata->vecs[i]->vecname) << " ";
    }
    cout << "\n\n";

    return 0;
}

/*
 * Callback function for sending a boolean signal (true if computational thread is running)(NULL allowed)
 *
 * This function is called each time the computation start or resume it's work.
 */
int simulation_runs_cb(bool not_running, int ident, void* userdata){
    if (not_running)
        cout << "thread_runs_cb: not running, id = " << this_thread::get_id() << endl;
    else
        cout << "thread_runs_cb: running, id = " << this_thread::get_id() << endl;

    return 0;
}

/*
 * Callback function for transferring a flag to caller, generated by ngspice
 * upon a call to function controlled_exit. (required) The controlled exit can be
 * initiated by the next calls:
 *
 * ngSpice_Command((char*) "bg_halt"); -- switch to command mode
 * ngSpice_Command((char*) "quit"); -- quit the procss
 *
 * After "quit" command the circuit is unloaded and ngspice thread stops. All the memory
 * will be freed. After this command, the ngspice can be completely reinitialize
 * by ngSpice_Init(...) and subsequent calls.
 *
 * => Use "quit" in the source destructor.
 * => Use exit_cb callback to set ng_alive = false;
 */
int exit_cb(int exitstatus, bool immediate, bool quitexit, int ident, void* userdata)
{
    cout << "exit_cb" << endl;
    return 0;
}

int main(int argc, char** argv){

    //register callbacks
    ngSpice_Init(getchar_cb, getstat_cb, exit_cb, data_cb, initdata_cb, simulation_runs_cb, nullptr);

    ngSpice_Command((char*) "source rc.cir");
    ngSpice_Command((char*) "bg_run");

    // wait until the process starts
    while(! ngSpice_running()){
        this_thread::sleep_for(chrono::milliseconds(20));
    }

    ngSpice_Command((char*) "bg_halt");
    ngSpice_Command((char*) "bg_run");
    while(! ngSpice_running()){
        this_thread::sleep_for(chrono::milliseconds(20));
    }


    // wait until the bg process terminates it's computations
    while(ngSpice_running()){
        this_thread::sleep_for(chrono::milliseconds(20));
    }

    return 0;
}

